variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - code-analysis

build:
  image: eclipse-temurin:21-jdk-alpine
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS -DskipTests -Dmaven.test.skip=true -T 4 package
  only:
    - branches
    - tags
  artifacts:
    expire_in: 10 mins
  tags: [ranking-info-runner]


verify:
  image: eclipse-temurin:21-jdk-alpine
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify
  only:
    - branches
    - tags
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
    expire_in: 10 mins
  tags: [ranking-info-runner]

sonarcloud-check:
  image: eclipse-temurin:21-jdk-alpine
  stage: code-analysis
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ./mvnw verify sonar:sonar -Dsonar.projectKey=hwesselmann_ranking-info
  only:
    - main
  artifacts:
    expire_in: 10 mins
  tags: [ranking-info-runner]
