version: '3'

volumes:
  postgresql_data:

services:
  db:
    image: postgres:12.2
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  web:
    image: rankinginfo:latest
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
      - RANKING_INFO_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DOMAIN=www.example.de
      - IMPRINT_NAME="Heinz Müller"
      - IMPRINT_STREET="Drosselgasse 4"
      - IMPRINT_ZIPCODE=54321
      - IMPRINT_CITY=Hintertupflingen
      - IMPRINT_PHONE=123456789
      - IMPRINT_MAIL="heinz@meinz.org"
    ports:
      - "3000:3000"
    depends_on:
      - db