services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ranking_info
      POSTGRES_USER: ranking_info
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-local-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ranking_info"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres-local-data:
