spring:
  application:
    name: ranking-info
  profiles:
    active: local_dev,log-console-info
  h2:
    console:
      enabled: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

server:
  port: 8080
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: true
  tomcat:
    accesslog:
      enabled: false

management:
  server:
    port: 9000
    address: 127.0.0.1

---
import:
  folder: /src/test/resources
spring:
  config:
    activate:
      on-profile: local_dev
