spring:
  datasource:
    url: jdbc:h2:file:${user.home}/ranking-info-dev;MODE=PostgreSQL;NON_KEYWORDS=USER;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

import:
  folder: ${IMPORT_FOLDER:${user.home}/ranking-import}
  schedule: "0 */30 * * * ?"
