--liquibase formatted sql

--changeset hwesselmann:test-001-ranking-testdata context:test dbms:h2
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (1, 10812345, 'Max', 'Mustermann', 'WTV', 'TC Musterhausen', 'GER', '2020-03-31', 'm', 2008, '213', 384, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (2, 10812346, 'Maik', 'Mustermann', 'WTV', 'Musterhausener TC', 'GER', '2020-03-31', 'm', 2008, '212', 387, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (3, 10812347, 'Oskar', 'Beispiel', 'BTV', 'Beispielhafter TSC', 'GER', '2020-03-31', 'm', 2008, '212', 387, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (4, 10712348, 'Hans', 'Hannsmann', 'TVN', 'Exemplaria SSV', 'GER', '2020-03-31', 'm', 2007, '190', 512, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (5, 10712349, 'Malik', 'Meier', 'BB', 'TTV Musterstadt', 'GER', '2020-03-31', 'm', 2007, '186', 519, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (6, 10612350, 'Anton', 'Austirol', 'STV', 'Musterhausener TC', 'GER', '2020-03-31', 'm', 2006, '177', 556, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (7, 10812351, 'Peter', 'Alexander', 'HTV', 'STV Beispiel', 'GER', '2020-03-31', 'm', 2008, '154', 651, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (8, 10512352, 'Karl', 'Heintz', 'TNB', 'Alter TC Exemplaris', 'GER', '2020-03-31', 'm', 2005, '154', 651, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (9, 10812353, 'Alfred', 'Willkommen', 'TVM', 'Sturm Musterstadt', 'GER', '2020-03-31', 'm', 2008, '132', 887, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (10, 10512354, 'Heiner', 'Lucky', 'STB', 'Musterhausener TC', 'GER', '2020-03-31', 'm', 2005, '120,5', 989, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (11, 10412355, 'Ben', 'Hur', 'WTB', 'TC Musterhausener', 'GER', '2020-03-31', 'm', 2004, '120,2', 990, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (12, 10312246, 'Luis', 'Armstark', 'HAM', 'Sturm Musterstadt', 'GER', '2020-03-31', 'm', 2003, '120', 995, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (13, 10212446, 'Linus', 'Torwart', 'SLH', 'Musterhausener TC', 'GER', '2020-03-31', 'm', 2002, '118', 1041, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (14, 10212546, 'Ole', 'Einar', 'TTV', 'Tabellenendener SC', 'GER', '2020-03-31', 'm', 2002, '116', 1090, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (15, 10312346, 'Kevin', 'Speck', 'RPF', 'ImSueden 1918', 'GER', '2020-03-31', 'm', 2003, '90', 1487, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (16, 10612346, 'Georg', 'Heiliger', 'TSA', 'Hoch zu Berge 17', 'GER', '2020-03-31', 'm', 2006, '87', 1697, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (17, 10512346, 'Moses', 'Melone', 'TMV', 'Gelber Elefant von 1947', 'GER', '2020-03-31', 'm', 2005, '48', 3912, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (18, 10912346, 'Abraham', 'Linkoln', 'WTV', 'Musterstädter Tennisklub', 'GER', '2020-03-31', 'm', 2009, '32', 4200, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (19, 10212346, 'Stefan', 'Rhabarber', 'BAD', 'TV Musterstadt-Nord', 'GER', '2020-03-31', 'm', 2002, '21', 4600, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (20, 10316346, 'Otto', 'Ottokar', 'WTV', 'VfL Musterhausen', 'GER', '2020-03-31', 'm', 2003, '18', 4732, 'all', false, false, false);
insert into ranking (id, dtbid, firstname, lastname, federation, club, nationality, period, gender, yob, points, rank, agegroup, include_all_players, only_yob_players, end_of_year_ranking) values (21, 10517346, 'Emil', 'Investigator', 'WTB', 'VfL Musterhausen', 'GER', '2020-03-31', 'm', 2005, '7', 9999, 'all', false, false, false);
